variable "PROJECT_NAME" {}
variable "REGION" {}
variable "CIDR" {}
variable "PUB-SUB-1-CIDR" {}
variable "PUB-SUB-2-CIDR" {}
variable "PRIV-SUB-1-CIDR" {}
variable "PRIV-SUB-2-CIDR" {}
variable "AMI" {}
variable "INSTANCE_TYPE" {}
variable "MIN_SIZE" {}
variable "MAX_SIZE" {}
variable "DESIRED_CAPACITY" {}
variable "DOMAIN_NAME" {}
variable "HOSTED_ZONE" {}
variable "RECORD_NAME" {}
variable "DB_SUB_NAME" {}
variable "DB-USER" {}
variable "DB-PASS" {}
variable "DB-NAME" {}
