variable "PROJECT_NAME" {}
variable "AMI" {}
variable "INSTANCE_TYPE" {}
variable "WEB_SG_ID" {}
variable "MIN_SIZE" {}
variable "MAX_SIZE" {}
variable "PUB-SUB-1-ID" {}
variable "PUB-SUB-2-ID" {}
variable "TG-ARN" {}
variable "DESIRED_CAPACITY" {}
